
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const  Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-gray-50">
        {/* Sidebar on Left */}
        <Sidebar />

        {/* Main Content Area */}
        <main className="flex-1 p-10">
          {children}
        </main>
      </body>
    </html>
  );
}